name: Android Build

on:
  push:
    branches:
      - master

jobs:
  buildAPK:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
        
      - name: Build Debug Apk
        run: ./gradlew :app:assembleDebug
